/*
 * Test Vector Generator for Cross-Language Compatibility Testing.
 *
 * This class generates deterministic test vectors for verifying Flutter
 * implementations of Takamaka encryption utilities.
 *
 * Run with: mvn test-compile exec:java -Dexec.mainClass="io.takamaka.extra.utils.TestVectorGenerator"
 */
package io.takamaka.extra.utils;

import io.takamaka.extra.beans.EncMessageBean;
import io.takamaka.wallet.exceptions.WalletException;
import io.takamaka.wallet.utils.TkmSignUtils;
import org.bouncycastle.crypto.digests.SHA3Digest;

import javax.crypto.Cipher;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.util.Base64;

/**
 * Generates test vectors for cross-language encryption compatibility testing.
 *
 * Test vectors are deterministic where possible (fixed IV/nonce) to allow
 * exact comparison between Java and Flutter implementations.
 */
public class TestVectorGenerator {

    public static void main(String[] args) throws Exception {
        System.out.println("=== Takamaka Encryption Test Vectors ===");
        System.out.println("Generated by Java reference implementation");
        System.out.println("Use these vectors to verify Flutter port compatibility");
        System.out.println();

        generatePBKDF2Vectors();
        System.out.println();

        generateSHA3256Vectors();
        System.out.println();

        generateAesCbcVectors();
        System.out.println();

        generateAesGcmVectors();
        System.out.println();

        generateEncryptDecryptRoundTripVectors();
        System.out.println();

        System.out.println("=== Test Vector Generation Complete ===");
    }

    /**
     * Generate PBKDF2-HMAC-SHA512 key derivation test vectors.
     */
    private static void generatePBKDF2Vectors() throws Exception {
        System.out.println("--- PBKDF2-HMAC-SHA512 Test Vectors ---");

        String[][] testCases = {
            {"password", "salt", "20000", "256"},
            {"test-password-12345", "test-scope", "20000", "256"},
            {"complex!@#$%^&*()password", "unicode-scope-日本語", "20000", "256"},
            {"symmetric-key-400chars-abcdefghijklmnopqrstuvwxyz", "conversation-salt-32chars", "20000", "256"},
        };

        for (String[] tc : testCases) {
            String password = tc[0];
            String salt = tc[1];
            int iterations = Integer.parseInt(tc[2]);
            int keyLengthBits = Integer.parseInt(tc[3]);

            PBEKeySpec spec = new PBEKeySpec(
                password.toCharArray(),
                salt.getBytes(StandardCharsets.UTF_8),
                iterations,
                keyLengthBits
            );
            SecretKeyFactory skf = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA512");
            byte[] key = skf.generateSecret(spec).getEncoded();

            System.out.println("PBKDF2 Vector:");
            System.out.println("  password: \"" + password + "\"");
            System.out.println("  salt: \"" + salt + "\"");
            System.out.println("  iterations: " + iterations);
            System.out.println("  keyLengthBits: " + keyLengthBits);
            System.out.println("  derivedKey_hex: \"" + bytesToHex(key) + "\"");
            System.out.println("  derivedKey_b64url: \"" + TkmSignUtils.fromByteArrayToB64URL(key) + "\"");
            System.out.println();
        }
    }

    /**
     * Generate SHA3-256 hash test vectors.
     */
    private static void generateSHA3256Vectors() throws Exception {
        System.out.println("--- SHA3-256 Test Vectors ---");

        String[] inputs = {
            "Hello, World!",
            "Test input string",
            "My Conversation",
            "unicode-日本語-\uD83D\uDE00",
            "The quick brown fox jumps over the lazy dog",
        };

        for (String input : inputs) {
            SHA3Digest digest = new SHA3Digest(256);
            byte[] inputBytes = input.getBytes(StandardCharsets.UTF_8);
            digest.update(inputBytes, 0, inputBytes.length);
            byte[] hash = new byte[digest.getDigestSize()];
            digest.doFinal(hash, 0);

            System.out.println("SHA3-256 Vector:");
            System.out.println("  input: \"" + input + "\"");
            System.out.println("  hash_hex: \"" + bytesToHex(hash) + "\"");
            System.out.println("  hash_b64url: \"" + TkmSignUtils.fromByteArrayToB64URL(hash) + "\"");
            System.out.println();
        }
    }

    /**
     * Generate AES-CBC encryption test vectors with fixed IV.
     */
    private static void generateAesCbcVectors() throws Exception {
        System.out.println("--- AES-CBC (v0_1_a) Test Vectors ---");

        // Test case 1: Simple text
        generateAesCbcVector(
            "test-password-12345",
            "Hello, World!",
            "test-scope",
            hexToBytes("00112233445566778899aabbccddeeff") // Fixed 16-byte IV
        );

        // Test case 2: Unicode content
        generateAesCbcVector(
            "unicode-password",
            "Hello, \uD83D\uDE00 World! 中文",
            "unicode-scope",
            hexToBytes("112233445566778899aabbccddeeff00")
        );

        // Test case 3: Longer content
        generateAesCbcVector(
            "long-content-password",
            "This is a longer message that spans multiple AES blocks to test proper CBC chaining.",
            "long-scope",
            hexToBytes("ffeeddccbbaa99887766554433221100")
        );
    }

    private static void generateAesCbcVector(String password, String content, String scope, byte[] iv) throws Exception {
        // Derive key using PBKDF2
        PBEKeySpec spec = new PBEKeySpec(
            password.toCharArray(),
            scope.getBytes(StandardCharsets.UTF_8),
            20000,
            256
        );
        SecretKeyFactory skf = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA512");
        byte[] key = skf.generateSecret(spec).getEncoded();
        SecretKeySpec keySpec = new SecretKeySpec(key, "AES");

        // Encrypt with AES-CBC
        Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
        cipher.init(Cipher.ENCRYPT_MODE, keySpec, new IvParameterSpec(iv));
        byte[] ciphertext = cipher.doFinal(content.getBytes(StandardCharsets.UTF_8));

        System.out.println("AES-CBC Vector:");
        System.out.println("  password: \"" + password + "\"");
        System.out.println("  content: \"" + content + "\"");
        System.out.println("  scope: \"" + scope + "\"");
        System.out.println("  iv_hex: \"" + bytesToHex(iv) + "\"");
        System.out.println("  iv_b64url: \"" + TkmSignUtils.fromByteArrayToB64URL(iv) + "\"");
        System.out.println("  ciphertext_hex: \"" + bytesToHex(ciphertext) + "\"");
        System.out.println("  ciphertext_b64url: \"" + TkmSignUtils.fromByteArrayToB64URL(ciphertext) + "\"");
        System.out.println("  derivedKey_hex: \"" + bytesToHex(key) + "\"");
        System.out.println();
    }

    /**
     * Generate AES-GCM encryption test vectors with fixed nonce.
     */
    private static void generateAesGcmVectors() throws Exception {
        System.out.println("--- AES-GCM (v0_2_a_stream_gcm) Test Vectors ---");

        // Test case 1: Simple text
        generateAesGcmVector(
            "test-password-12345",
            "Hello, World!",
            "test-salt-32chars-for-key-deriv",
            hexToBytes("000102030405060708090a0b") // Fixed 12-byte nonce
        );

        // Test case 2: Longer content
        generateAesGcmVector(
            "gcm-password",
            "This is authenticated encrypted content using AES-GCM mode.",
            "gcm-salt-32-characters-exactly!",
            hexToBytes("0f0e0d0c0b0a09080706050f")
        );
    }

    private static void generateAesGcmVector(String password, String content, String salt, byte[] nonce) throws Exception {
        // Derive key using PBKDF2
        PBEKeySpec spec = new PBEKeySpec(
            password.toCharArray(),
            salt.getBytes(StandardCharsets.UTF_8),
            20000,
            256
        );
        SecretKeyFactory skf = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA512");
        byte[] key = skf.generateSecret(spec).getEncoded();
        SecretKeySpec keySpec = new SecretKeySpec(key, "AES");

        // Encrypt with AES-GCM (128-bit tag)
        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding", "BC");
        GCMParameterSpec gcmSpec = new GCMParameterSpec(128, nonce);
        cipher.init(Cipher.ENCRYPT_MODE, keySpec, gcmSpec);
        byte[] ciphertextWithTag = cipher.doFinal(content.getBytes(StandardCharsets.UTF_8));

        System.out.println("AES-GCM Vector:");
        System.out.println("  password: \"" + password + "\"");
        System.out.println("  content: \"" + content + "\"");
        System.out.println("  salt: \"" + salt + "\"");
        System.out.println("  nonce_hex: \"" + bytesToHex(nonce) + "\"");
        System.out.println("  nonce_b64url: \"" + TkmSignUtils.fromByteArrayToB64URL(nonce) + "\"");
        System.out.println("  ciphertextWithTag_hex: \"" + bytesToHex(ciphertextWithTag) + "\"");
        System.out.println("  ciphertextWithTag_b64url: \"" + TkmSignUtils.fromByteArrayToB64URL(ciphertextWithTag) + "\"");
        System.out.println("  derivedKey_hex: \"" + bytesToHex(key) + "\"");
        System.out.println();
    }

    /**
     * Generate round-trip encryption/decryption test vectors using TkmEncryptionUtils.
     */
    private static void generateEncryptDecryptRoundTripVectors() throws Exception {
        System.out.println("--- Round-Trip Test Vectors (using TkmEncryptionUtils) ---");

        String[][] testCases = {
            {"test-password", "Hello, World!", "test-scope"},
            {"symmetric-key-for-conversation", "This is a chat message content.", "conversation-salt"},
            {"unicode-key-日本語", "Unicode content: 日本語 \uD83D\uDE00", "unicode-scope-\uD83C\uDF89"},
        };

        for (String[] tc : testCases) {
            String password = tc[0];
            String content = tc[1];
            String scope = tc[2];

            EncMessageBean encrypted = TkmEncryptionUtils.toPasswordEncryptedContent(
                password, content, scope, "v0_1_a"
            );

            System.out.println("Round-Trip Vector:");
            System.out.println("  password: \"" + password + "\"");
            System.out.println("  content: \"" + content + "\"");
            System.out.println("  scope: \"" + scope + "\"");
            System.out.println("  tkVersion: \"" + encrypted.getTkVersion() + "\"");
            System.out.println("  passwordHashAlgorithm: \"" + encrypted.getPasswordHashAlgorithm() + "\"");
            System.out.println("  iterations: " + encrypted.getIterations());
            System.out.println("  transformation: \"" + encrypted.getTransformation() + "\"");
            System.out.println("  keySpecAlgorithm: \"" + encrypted.getKeySpecAlgorithm() + "\"");
            System.out.println("  outputKeyLengthBit: " + encrypted.getOutputKeyLengthBit());
            System.out.println("  encoding: \"" + encrypted.getEncoding() + "\"");
            System.out.println("  iv_b64url: \"" + encrypted.getEncryptedMessage()[0] + "\"");
            System.out.println("  ciphertext_b64url: \"" + encrypted.getEncryptedMessage()[1] + "\"");

            // Verify decryption works
            String decrypted = TkmEncryptionUtils.fromPasswordEncryptedContent(password, scope, encrypted);
            System.out.println("  decrypted: \"" + decrypted + "\"");
            System.out.println("  matches: " + content.equals(decrypted));
            System.out.println();
        }
    }

    // Utility methods
    private static String bytesToHex(byte[] bytes) {
        StringBuilder sb = new StringBuilder();
        for (byte b : bytes) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
    }

    private static byte[] hexToBytes(String hex) {
        int len = hex.length();
        byte[] data = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {
            data[i / 2] = (byte) ((Character.digit(hex.charAt(i), 16) << 4)
                    + Character.digit(hex.charAt(i + 1), 16));
        }
        return data;
    }
}
